#!/usr/bin/env bash
#
# Runs Celestine in a local WordPress, without Docker.
#
# Provisions a WordPress install backed by SQLite in .wp-local/, symlinks the
# theme into it so edits are live, seeds enough content to exercise every
# template, and serves it with PHP's built-in server.
#
# Usage:
#   bash tools/dev-server.sh                provision if needed, then serve
#   bash tools/dev-server.sh --fresh        rebuild the install from scratch
#   bash tools/dev-server.sh --port 9000    serve on a different port
#   bash tools/dev-server.sh --no-serve     provision only, do not serve
#
set -euo pipefail

THEME_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SITE_DIR="${THEME_DIR}/.wp-local"
PORT=8420
FRESH=0
SERVE=1

while [[ $# -gt 0 ]]; do
	case "$1" in
		--fresh)    FRESH=1; shift ;;
		--no-serve) SERVE=0; shift ;;
		--port)     PORT="$2"; shift 2 ;;
		-h|--help)  sed -n '2,14p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
		*)          echo "unknown option: $1" >&2; exit 1 ;;
	esac
done

SITE_URL="http://localhost:${PORT}"

export WP_CLI_PHP_ARGS='-d error_reporting=E_ALL^E_DEPRECATED -d display_errors=0'

say() { printf '\033[2m%s\033[0m\n' "$*"; }
ok()  { printf '\033[32m%s\033[0m\n' "$*"; }
die() { printf '\033[31merror:\033[0m %s\n' "$*" >&2; exit 1; }

command -v php >/dev/null || die "php not found. brew install php"
command -v wp  >/dev/null || die "wp-cli not found. brew install wp-cli"

# Asked directly rather than through `php -m | grep -q`, which trips pipefail:
# grep exits on the first match and SIGPIPEs php, failing the pipeline.
php -r 'exit( extension_loaded( "pdo_sqlite" ) ? 0 : 1 );' \
	|| die "the pdo_sqlite PHP extension is required but not enabled"

wpcli() { wp --path="${SITE_DIR}" "$@" 2>&1 | grep -viE 'deprecated|php-cli-tools|react/promise' || true; }

if [[ "${FRESH}" == "1" ]]; then
	say "removing ${SITE_DIR}"
	rm -rf "${SITE_DIR}"
fi

if [[ ! -f "${SITE_DIR}/wp-includes/version.php" ]]; then
	mkdir -p "${SITE_DIR}"

	if [[ -f "${THEME_DIR}/.wp-core/wp-includes/version.php" ]]; then
		say "copying WordPress from .wp-core"
		rsync -a --exclude 'wp-content/themes/twenty*' "${THEME_DIR}/.wp-core/" "${SITE_DIR}/"
	else
		say "downloading WordPress"
		curl -sL https://wordpress.org/latest.tar.gz | tar -xz -C "${SITE_DIR}" --strip-components=1
	fi
fi

SQLITE_DIR="${SITE_DIR}/wp-content/plugins/sqlite-database-integration"

if [[ ! -f "${SQLITE_DIR}/db.copy" ]]; then
	say "installing the SQLite database integration plugin"
	mkdir -p "${SITE_DIR}/wp-content/plugins"
	TMP_ZIP="$(mktemp -t sqlite-di).zip"
	curl -sL -o "${TMP_ZIP}" https://downloads.wordpress.org/plugin/sqlite-database-integration.zip
	unzip -oq "${TMP_ZIP}" -d "${SITE_DIR}/wp-content/plugins/"
	rm -f "${TMP_ZIP}"
fi

mkdir -p "${SITE_DIR}/wp-content/database"

if [[ ! -f "${SITE_DIR}/wp-content/db.php" ]]; then
	sed -e "s#{SQLITE_IMPLEMENTATION_FOLDER_PATH}#${SQLITE_DIR}#g" \
	    -e "s#{SQLITE_PLUGIN}#sqlite-database-integration/load.php#g" \
	    "${SQLITE_DIR}/db.copy" > "${SITE_DIR}/wp-content/db.php"
fi

if [[ ! -f "${SITE_DIR}/wp-config.php" ]]; then
	say "writing wp-config.php"
	cat > "${SITE_DIR}/wp-config.php" <<'PHPCONF'
<?php
/**
 * Local development configuration for the Celestine theme.
 * Generated by tools/dev-server.sh. Not part of the theme.
 */

define( 'DB_NAME', 'wordpress' );
define( 'DB_USER', '' );
define( 'DB_PASSWORD', '' );
define( 'DB_HOST', 'localhost' );
define( 'DB_CHARSET', 'utf8' );
define( 'DB_COLLATE', '' );

define( 'AUTH_KEY', 'celestine-local-1' );
define( 'SECURE_AUTH_KEY', 'celestine-local-2' );
define( 'LOGGED_IN_KEY', 'celestine-local-3' );
define( 'NONCE_KEY', 'celestine-local-4' );
define( 'AUTH_SALT', 'celestine-local-5' );
define( 'SECURE_AUTH_SALT', 'celestine-local-6' );
define( 'LOGGED_IN_SALT', 'celestine-local-7' );
define( 'NONCE_SALT', 'celestine-local-8' );

$table_prefix = 'wp_';

define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', false );
@ini_set( 'display_errors', 0 );
define( 'SCRIPT_DEBUG', true );

/*
 * WordPress caches the compiled output of theme.json; without this, edits to
 * theme.json, style variations and patterns do not appear until the caches are
 * flushed by hand.
 */
define( 'WP_DEVELOPMENT_MODE', 'theme' );

// A working copy must never be replaced by a download from the directory.
define( 'AUTOMATIC_UPDATER_DISABLED', true );
define( 'WP_AUTO_UPDATE_CORE', false );

define( 'WP_POST_REVISIONS', false );
define( 'DISABLE_WP_CRON', true );

if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', __DIR__ . '/' );
}

require_once ABSPATH . 'wp-settings.php';
PHPCONF
fi

# WordPress skips directories whose name starts with a dot when it scans a
# theme, so .wp-local is invisible to the scanner and this symlink back into the
# theme root does not recurse.
mkdir -p "${SITE_DIR}/wp-content/themes"
rm -rf "${SITE_DIR}/wp-content/themes/celestine"
ln -s "${THEME_DIR}" "${SITE_DIR}/wp-content/themes/celestine"

cat > "${SITE_DIR}/router.php" <<'PHPROUTER'
<?php
/**
 * Router for PHP's built-in server.
 *
 * Serves real files itself rather than returning false to let the server do it.
 *
 * That distinction matters here: the theme -- and any plugin under development
 * -- is symlinked into wp-content from a working copy outside the document
 * root, and the built-in server refuses to serve files it resolves to a path
 * outside that root. Returning false therefore produced a 404 for every font,
 * stylesheet and script reached through a symlink, while the HTML referencing
 * them looked perfectly correct. Reading the file here sidesteps the check.
 *
 * Generated by tools/dev-server.sh. Not part of the theme.
 */

$path = parse_url( $_SERVER['REQUEST_URI'], PHP_URL_PATH );
$file = realpath( __DIR__ . urldecode( $path ) );

if ( '/' !== $path && false !== $file && is_file( $file ) ) {
	$types = array(
		'css'   => 'text/css',
		'js'    => 'text/javascript',
		'mjs'   => 'text/javascript',
		'json'  => 'application/json',
		'map'   => 'application/json',
		'woff2' => 'font/woff2',
		'woff'  => 'font/woff',
		'ttf'   => 'font/ttf',
		'otf'   => 'font/otf',
		'eot'   => 'application/vnd.ms-fontobject',
		'svg'   => 'image/svg+xml',
		'png'   => 'image/png',
		'jpg'   => 'image/jpeg',
		'jpeg'  => 'image/jpeg',
		'gif'   => 'image/gif',
		'webp'  => 'image/webp',
		'avif'  => 'image/avif',
		'ico'   => 'image/x-icon',
		'mp4'   => 'video/mp4',
		'webm'  => 'video/webm',
		'mp3'   => 'audio/mpeg',
		'txt'   => 'text/plain',
		'xml'   => 'application/xml',
		'pdf'   => 'application/pdf',
	);

	$extension = strtolower( pathinfo( $file, PATHINFO_EXTENSION ) );

	// PHP inside wp-content must still execute, not be served as text.
	if ( 'php' !== $extension ) {
		header( 'Content-Type: ' . ( $types[ $extension ] ?? 'application/octet-stream' ) );
		header( 'Content-Length: ' . filesize( $file ) );
		header( 'Cache-Control: no-store' );
		readfile( $file );
		exit;
	}
}

require __DIR__ . '/index.php';
PHPROUTER

if ! wp --path="${SITE_DIR}" core is-installed 2>/dev/null; then
	say "installing WordPress"
	wpcli core install \
		--url="${SITE_URL}" \
		--title="Celestine (local)" \
		--admin_user=admin \
		--admin_password=password \
		--admin_email=dev@example.test \
		--skip-email >/dev/null

	wpcli theme activate celestine >/dev/null
	wpcli rewrite structure '/%postname%/' --hard >/dev/null

	say "seeding content"

	wpcli term create category Blog --slug=blog >/dev/null
	wpcli term create category Portfolio --slug=portfolio >/dev/null

	wpcli post create --post_type=post --post_status=publish --post_category=blog \
		--post_title="What p99 actually measures" \
		--post_content="Percentiles describe the shape of a distribution, not a typical request." >/dev/null
	wpcli post create --post_type=post --post_status=publish --post_category=blog \
		--post_title="On-call is a design problem" \
		--post_content="Pager load is a symptom. Every alert that fires more than once a quarter is a missing guardrail." >/dev/null
	wpcli post create --post_type=post --post_status=publish --post_category=blog \
		--post_title="Reading a flame graph without guessing" \
		--post_content="Width is time, not call count. The tall narrow towers are almost never the problem." >/dev/null

	wpcli post create --post_type=post --post_status=publish --post_category=portfolio \
		--post_title="Sharding a single-primary Postgres cluster" \
		--post_content="Moved a write-saturated primary onto sixteen shards with no scheduled downtime." >/dev/null
	wpcli post create --post_type=post --post_status=publish --post_category=portfolio \
		--post_title="An event pipeline that survives replays" \
		--post_content="Idempotent consumers and a compacted log, so a bad deploy is recoverable by replaying." >/dev/null
	wpcli post create --post_type=post --post_status=publish --post_category=portfolio \
		--post_title="Cutting cold start from 9s to 400ms" \
		--post_content="Most of it was class loading. The rest was a DNS lookup nobody had noticed." >/dev/null

	HOME_ID="$( wp --path="${SITE_DIR}" post create --post_type=page --post_status=publish \
		--post_title="Home" --porcelain 2>/dev/null | tail -1 )"
	WRITING_ID="$( wp --path="${SITE_DIR}" post create --post_type=page --post_status=publish \
		--post_title="Writing" --porcelain 2>/dev/null | tail -1 )"

	wpcli option update show_on_front page >/dev/null
	wpcli option update page_on_front "${HOME_ID}" >/dev/null
	wpcli option update page_for_posts "${WRITING_ID}" >/dev/null

	wpcli menu create "Primary" >/dev/null
	wpcli menu item add-post primary "${HOME_ID}" >/dev/null
	wpcli menu item add-post primary "${WRITING_ID}" >/dev/null
	wpcli menu item add-custom primary "Contact" "#contact" >/dev/null
fi

if [[ ! -d "${SITE_DIR}/wp-content/plugins/query-monitor" ]]; then
	say "installing Query Monitor"
	wpcli plugin install query-monitor --activate >/dev/null
fi

mkdir -p "${SITE_DIR}/wp-content/mu-plugins"
cp "${THEME_DIR}/tools/dev-markers.php" "${SITE_DIR}/wp-content/mu-plugins/celestine-dev-markers.php"
cp "${THEME_DIR}/tools/dev-guard.php" "${SITE_DIR}/wp-content/mu-plugins/celestine-dev-guard.php"

: > "${SITE_DIR}/wp-content/debug.log"

ok "ready"
cat <<EOF

  Site        ${SITE_URL}
  Admin       ${SITE_URL}/wp-admin  (admin / password)
  Editor      ${SITE_URL}/wp-admin/site-editor.php
  Theme       symlinked, edits are live
  PHP log     .wp-local/wp-content/debug.log
  Install     .wp-local/  (gitignored, rebuild with --fresh)

EOF

if [[ "${SERVE}" == "0" ]]; then
	exit 0
fi

say "serving on ${SITE_URL} — Ctrl-C to stop"
#
# -d opcache.enable=0: PHP's built-in server runs under the "cli-server" SAPI,
# which honours opcache.enable (only enable_cli is off), and the default
# revalidate_freq of 2 seconds makes an edit to a pattern look like a failed
# save rather than a cache.
#
exec php -d opcache.enable=0 -S "localhost:${PORT}" -t "${SITE_DIR}" "${SITE_DIR}/router.php"
